name: "Check PR merge conflicts"
on:
  workflow_call:

jobs:
  pr-conflict-Check:
    name: 'Check PR status: conflicts and resolution'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Bullfrog Secure Runner
        uses: bullfrogsec/bullfrog@v0
        with:
          egress-policy: audit

      - name: check if PRs are dirty
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "conflicts"
          removeOnDirtyLabel: "state: conflict resolved"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
          commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request shortly."
